var num_2 = 5;
var num_1 = 8;
console.log("Addition");
console.log("".concat(num_1, " + ").concat(num_2, " = ").concat(num_1 + num_2, "\n"));
console.log("Subtraction");
console.log("".concat(num_1, " - ").concat(num_2, " = ").concat(num_1 - num_2, "\n"));
console.log("Multiplication");
console.log("".concat(num_1, " * ").concat(num_2, " = ").concat(num_1 * num_2, "\n"));
console.log("Division");
console.log("".concat(num_1, " / ").concat(num_2, " = ").concat(num_1 / num_2, "\n"));
